pipeline:
  name: pipeline1
  identifier: pipeline1
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.GitHubConn
        build: <+input>
  stages:
    - stage:
        name: MyBuild1
        identifier: MyBuild1
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: |-
                      echo "Listing files in repo:"
                      ls -l
                      echo "Contents of sample.txt:"
                      cat sample.txt
